routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Redirect the root page to login page
Route::get('/', function () {
    return redirect('login');
});

/*
 * Show the login form and handle login/logout operation.
 * Registration and Password Reset is disabled.
 * Original code: Auth::routes();
 */
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Admin Dashboard
Route::get('/', 'AdminController@index')->name('dashbaord');

// QR
Route::group(['middleware' => 'auth'], function () {
    Route::get('assets/barcode', 'AssetController@getBarcode')->name('assets.barcode');
    Route::get('assets/{id}/landing', 'AssetController@landing')->name('assets.landing');
});

// QR
Route::group(['middleware' => 'auth', 'prefix' => 'assets'], function () {
    Route::get('import', 'AssetController@getImport')->name('assets.import.index');
    Route::post('import', 'AssetController@postImport')->name('assets.import');
});

// Maintenance
Route::group(['middleware' => 'auth'], function () {
    Route::get('assets/{id}/maintenance/create', 'MaintenanceController@create')->name('maintenances.create');
    Route::post('assets/{id}/maintenance', 'MaintenanceController@store')->name('maintenances.store');
    Route::get('assets/{id}/maintenance/{maintenance_id}/edit', 'MaintenanceController@edit')->name('maintenances.edit');
    Route::put('assets/{id}/maintenance/{maintenance_id}', 'MaintenanceController@update')->name('maintenances.update');
});

// Bootstrap-Table list
Route::group(['middleware' => 'auth', 'prefix' => '/list'], function () {
    Route::get('assets', 'AssetController@list')->name('assets.list');
    Route::get('departments', 'DepartmentController@list')->name('departments.list');
    Route::get('locations', 'LocationController@list')->name('locations.list');
    Route::get('maintenances', 'MaintenanceController@list')->name('maintenances.list');
    Route::get('models', 'AssetModelController@list')->name('models.list');
    Route::get('vendors', 'VendorController@list')->name('vendors.list');
});

// Assets list
Route::group(['middleware' => 'auth'], function () {
    Route::get('/assets/{id}/maintenances', 'MaintenanceController@maintenanceList')->name('assets.maintenances');
    Route::get('/departments/{id}/assets', 'DepartmentController@assetsList')->name('departments.assets');
    Route::get('/locations/{id}/assets', 'LocationController@assetsList')->name('locations.assets');
    Route::get('/models/{id}/assets', 'AssetModelController@assetsList')->name('models.assets');
    Route::get('/orders/{id}/assets', 'OrderController@assetsList')->name('orders.assets');
    Route::get('/vendors/{id}/assets', 'VendorController@assetsList')->name('vendors.assets');
});

// Managements
Route::group(['middleware' => 'auth'], function () {
    Route::resource('assets', 'AssetController');
    Route::resource('departments', 'DepartmentController');
    Route::resource('locations', 'LocationController');
    Route::resource('models', 'AssetModelController');
    Route::resource('orders', 'OrderController');
    Route::resource('vendors', 'VendorController');
    Route::post('categories', 'CategoryController@store')->name('categories.store');
});

resources/views/layouts/bootstrap-table.blade.php
<script type="text/javascript">
    // Add control buttons for list page
    function addActions(value, row) {
        return [
                '<button id="edit" class="btn btn-outline-dark mr-1" aria-label="detail">' +
                    '<span class="fa fa-pencil" data-glyph="pencil"></span> Edit' +
                '</button>',
                {{-- Detail button (DISABLED)
                `<button id="detail" class="btn btn-info mr-1" aria-label="edit">` +
                    '<span class="fa fa-list"></span> ' +
                    '<span class="d-none d-md-inline"> Detail</span>' +
                '</button>', --}}
                {{-- Delete button (DISABLED)
                '<button id="delete" class="btn btn-danger" aria-label="delete">' +
                    '<span class="fa fa-trash"></span> ' +
                    '<span class="d-none d-md-inline"> Delete</span>' +
                '</button>' --}}
        ].join('');
    }

    window.actionEvents = {
        'click #edit': function (e, value, row) {
            window.location.assign(`/@yield('category')/${row['id']}/edit`);
        },
        {{-- Detail button event (DISABLED)
        'click #detail': function (e, value, row) {
            window.location.assign(`/@yield('category')/${row['id']}`);
        },
        --}}
        {{-- Delete button event (DISABLED)
        'click #delete': function (e, value, row) {
            e.preventDefault();
            $.ajax({
                url: `/admin/@yield('category')/${row['id']}`,
                type: 'POST',
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                beforeSend: function () {
                    if (!confirm('Are you sure to delete the selected data?')) {
                        return false;
                    }
                },
                success: function () {
                    $('.table').bootstrapTable('refresh');
                },
                error: function () {
                    alert('Something happened wrong.');
                }
            });
        }
        --}}
    };

        function phoneCall(value) {
            return `<a href="tel:${value}">${value}</a>`;
        }

        function vendorDetail(value, row) {
            return `<a href="/vendors/${row['id']}">${value}</a>`;
        }

        function modelDetail(value, row) {
            return `<a href="/models/${row['id']}">${value}</a>`;
        }

        function locationDetail(value, row) {
            return `<a href="/locations/${row['id']}">${value}</a>`;
        }

        function assetDetail(value, row) {
            return `<a href="/assets/${row['id']}">${value}</a>`;
        }

        // Format the cell for Asset Management
        function assetModelDetail(value, row) {
            return `<a href="/models/${row['asset_model_id']}">${value}</a>`;
        }

        function assetLocationDetail(value, row) {
            return `<a href="/locations/${row['location_id']}">${value}</a>`;
        }

        function assetVendorDetail(value, row) {
            return `<a href="/vendors/${row['vendor_id']}">${value}</a>`;
        }

    @if(Route::currentRouteName() === 'assets.index')
        // Format the cell and highlight the asset
        function warrantyCell(value) {
            var warrantyDate = new Date(value);
            var today = new Date();
            var diff = Math.round((warrantyDate - today)/86400000);
            switch (true) {
                case (diff < 365 && diff >= 180):
                    return {css: {"background-color": "#daffb3"}};
                case (diff < 180 && diff >= 90):
                    return {css: {"background-color": "#ffffbb"}};
                case (diff < 90):
                    return {css: {"background-color": "#ffad99", "color": "white"}};
                default:
                    return {};
            }
        }

        function getBarcode() {
            var selectedIDs = $.map($('.table').bootstrapTable('getSelections'), function (row) {
                return row.id;
            });
            $.ajax({
                url: '{{ route('assets.barcode') }}',
                type: 'GET',
                data: {id: selectedIDs},
                beforeSend: function () {
                    if (selectedIDs.length === 0) {
                        alert('You didn\'t select any assets.');
                        return false;
                    }
                },
                success: function(data) {
                    document.write(data);
                },
                error: function(error) {
                    alert('Something went wrong. Please check web console and contact administrator.');
                    console.error(error.responseJSON.message);
                }
            });
        }
    @endif
</script>

resources/views/layouts/form.blade.php
@extends('layouts.master')

@section('style')
    <link rel="stylesheet" href="{{ asset('assets/css/selectize.default.css') }}">
@endsection

@section('javascript')
    <script src="{{ asset('assets/js/selectize.min.js') }}"></script>
    @yield('additionalJS')
@endsection

@section('actionButtons')
    <a class="btn btn-outline-dark mr-3" href="@yield('returnPage')">
        <span class="fa fa-chevron-left"></span>
        <span class="d-none d-sm-inline"> Back</span>
    </a>
@endsection

@section('contents')
    @include('layouts.message')
    <div class="card">
        <div class="card-body">
            <form class="form form-horizontal" id="form-@yield('category')" method="POST" action="@yield('actionPage')">
                {{ csrf_field() }}
                @yield('form')
            </form>
        </div>
        <div class="card-footer text-right">
            <a class="btn btn-outline-dark" href="@yield('returnPage')">
                <span class="fa fa-times"></span> Cancel
            </a>
            <button type="submit" class="btn btn-primary" form="form-@yield('category')">
                @if(strpos(Route::currentRouteName(), 'create'))
                    <span class="fa fa-plus"></span> Create
                @elseif(strpos(Route::currentRouteName(), 'import'))
                    <span class="fa fa-upload"></span> Import
                @else
                    <span class="fa fa-pencil"></span> Edit
                @endif
            </button>
        </div>
    </div>
    @yield('modals')
@endsection

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title') - IT Asset Management System</title>
    <link rel="stylesheet" href="{{ asset('assets/css/app.css') }}">
    <style type="text/css">
        html, body {
            height: 100%;
        }
        body {
            display: flex;
            align-items: center;
        }
    </style>
</head>
<body>
<div class="container">
    @yield('contents')
    <noscript>This site is JavaScript-required. Please consider to enable JavaScript in your browser.</noscript>
    <script src="{{ asset('assets/js/app.js') }}"></script>
</div>
</body>
</html>

resources/views/layouts/list.blade.php
@extends('layouts.master')

@section('style')
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap-table.css') }}">
@endsection

@section('javascript')
    <script src="{{ asset('assets/js/bootstrap-table.js') }}"></script>
    @include('layouts.bootstrap-table')
@endsection

@section('contents')
    @include('layouts.message')
    <div id="toolbar">
        <a class="btn btn-primary" href="@yield('createPage')" aria-label="create">
            <span class="fa fa-plus"></span> Add
        </a>
        @if(Route::currentRouteName() === 'assets.index')
            <button type="button" class="btn btn-info" onClick="getBarcode()" aria-label="barcode">
                <span class="fa fa-barcode"></span> Barcode
            </button>
            <a class="btn btn-warning" href="{{ route('assets.import.index') }}" aria-label="import">
                <span class="fa fa-upload"></span> Import
            </a>
        @endif
        {{--<a class="btn btn-danger" href="" aria-label="delete">--}}
            {{--<span class="fa fa-trash"></span> Delete--}}
        {{--</a>--}}
    </div>
    <div class="table-responsive">
        @yield('table')
    </div>
@endsection

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}"/>
    <meta name="theme-color" content="#f8f9fa"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>@yield('title') - IT Asset Management System</title>
    <link rel="stylesheet" href="{{ asset('assets/css/app.css') }}">
    @yield('style')
</head>
<body>
    @include('layouts.navbar')
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12 mx-auto">
                <div class="d-flex align-items-center pt-3 pb-2">
                    @yield('actionButtons')
                    <h3 class="mb-0 order-6">@yield('title')</h3>
                </div>
                @yield('contents')
            </div>
        </div>
        <div id="javascript">
            <noscript>This site is JavaScript-required. Please consider to enable JavaScript in your browser.</noscript>
            <script src="{{ asset('assets/js/app.js') }}"></script>
            @yield('javascript')
        </div>
    </main>
</body>
</html>

resources/views/layouts/message.blade.php
@if(Session::has('success'))
    <div class="alert alert-success" role="alert">
        <span class="fa fa-check-circle"></span> {{ Session::get('success') }}
    </div>
@endif

@if(count($errors))
    <div class="alert alert-danger" role="alert">
        <span class="fa fa-times-circle"></span> The following problems occurred:<p>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@guest
    <div class="alert alert-info" role="alert">
        <span class="fa fa-info"></span> Please login before you access the system.
    </div>
@endguest

resources/views/layouts/navbar.blade.php
<!-- Responsive Navbar -->
<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light" role="navigation">
    <a class="navbar-brand d-none d-sm-block" href="/">IT Asset Management System</a>
    <a class="navbar-brand d-sm-none" href="#">ITAM System</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar contents -->
    <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ route('dashbaord') }}">Dashboard</a>
            <a class="nav-item nav-link" href="{{ route('assets.index') }}">Assets</a>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Other Managements<span
                        class="caret"></span></a>
                <div class="dropdown-menu" aria-labelledby="otherManagementDropdown">
                    <a class="dropdown-item" href="{{ route('departments.index') }}">Departments</a>
                    <a class="dropdown-item" href="{{ route('locations.index') }}">Locations</a>
                    <a class="dropdown-item" href="{{ route('models.index') }}">Models</a>
                    {{--<a class="dropdown-item" href="{{ route('orders.index') }}">Orders</a>--}}
                    <a class="dropdown-item" href="{{ route('vendors.index') }}">Vendors</a>
                </div>
            </li>
        </ul>
        <ul class="d-md-none dropdown-divider"></ul>
        <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            <a class="nav-item nav-link">User: {{ (Auth::check()) ? Auth::user()->name : 'Direct Access' }}</a>
            <a class="nav-item nav-link" href="#" onclick="document.getElementById('logout-form').submit();">Logout</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </ul>
    </div>
</nav>

resources/views/layouts/show.blade.php
@extends('layouts.master')

@section('style')
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap-table.css') }}">
@endsection

@section('javascript')
    <script src="{{ asset('assets/js/bootstrap-table.js') }}"></script>
    @include('layouts.bootstrap-table')
@endsection

@section('actionButtons')
    <a class="btn btn-outline-dark mr-3" href="javascript:window.history.back();">
        <span class="fa fa-chevron-left"></span>
        <span class="d-none d-sm-inline"> Back</span>
    </a>
    <a class="btn btn-outline-dark ml-auto order-12" href="@yield('editPage')" aria-label="create">
        <span class="fa fa-pencil"></span> Edit
    </a>
@endsection

@section('contents')
    <ul class="nav nav-pills mb-2" id="detailTab" role="tablist">
        @yield('tab-items')
    </ul>

    <div class="tab-content" id="tab-content">
        @yield('tab-contents')
    </div>
@endsection